version: '3.8'

services:
  omnivore-api:
    image: ghcr.io/pranav-karra-3301/omnivore:latest
    container_name: omnivore-api
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - OMNIVORE_DATA_DIR=/var/lib/omnivore
      - DATABASE_URL=postgresql://omnivore:${POSTGRES_PASSWORD}@postgres:5432/omnivore
      - REDIS_URL=redis://redis:6379
      - SELENIUM_URL=http://selenium:4444
    volumes:
      - omnivore-data:/var/lib/omnivore
      - ./configs:/etc/omnivore/configs:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - omnivore-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  postgres:
    image: postgres:16-alpine
    container_name: omnivore-postgres
    environment:
      - POSTGRES_DB=omnivore
      - POSTGRES_USER=omnivore
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8 --locale=C"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omnivore -d omnivore"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - omnivore-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  redis:
    image: redis:7-alpine
    container_name: omnivore-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - omnivore-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  # Browser automation for dynamic content
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: omnivore-selenium
    environment:
      - SE_VNC_VIEW_ONLY=1
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=300
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    profiles:
      - browser
    networks:
      - omnivore-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: omnivore-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - omnivore-api
    restart: unless-stopped
    networks:
      - omnivore-network
    profiles:
      - proxy

volumes:
  omnivore-data:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
  omnivore-network:
    driver: bridge
