site_name: Omnivore
site_description: High-performance web crawler and content extraction framework for Rust
site_url: https://omnivore.readthedocs.io
site_author: Omnivore Team
repo_url: https://github.com/Pranav-Karra-3301/omnivore
repo_name: Pranav-Karra-3301/omnivore
edit_uri: edit/master/docs/
copyright: Copyright &copy; 2024 Omnivore Team

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - toc.follow

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-\.]+'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Pranav-Karra-3301/omnivore

nav:
  - Home:
    - Overview: index.md
    - Quickstart: quickstart.md
    - Installation: installation.md
    - Configuration: configuration.md
    
  - CLI Reference:
    - Overview: cli.md
    - Crawl Command: cli-crawl.md
    - Git Command: cli-git.md
    
  - API:
    - REST API: api/rest.md
    - GraphQL API: api/graphql.md
    
  - Architecture:
    - Overview: architecture/overview.md
    - Crawler: architecture/crawler.md
    - Parser: architecture/parser.md
    - Storage: architecture/storage.md
    - Knowledge Graph: architecture/knowledge-graph.md
      
  - Guides:
    - Writing Extractors: guides/extractors.md
    - Politeness & robots.txt: guides/politeness.md
    
  - Tutorials:
    - Build a Graph from a Site: tutorials/graph-from-site.md
      
  - Deployment:
    - Docker: deployment/docker.md
    - Homebrew: deployment/homebrew.md
    
  - Development:
    - Build & Test: development/build.md
    - Contributing: development/contributing.md